<?php

namespace ASDLabs\Finance\Core;

final class Schema {
	const VERSION = '2026.04.22-alpha16';

	public static function get_queries() {
		global $wpdb;

		$charset_collate = $wpdb->get_charset_collate();

		$accounts            = Tables::name( 'accounts' );
		$contacts            = Tables::name( 'contacts' );
		$documents           = Tables::name( 'documents' );
		$document_files      = Tables::name( 'document_files' );
		$source_links        = Tables::name( 'source_links' );
		$payments            = Tables::name( 'payments' );
		$payment_allocations = Tables::name( 'payment_allocations' );
		$employee_profiles   = Tables::name( 'employee_profiles' );
		$employee_advances   = Tables::name( 'employee_advances' );
		$payroll_periods     = Tables::name( 'payroll_periods' );
		$service_profiles    = Tables::name( 'service_profiles' );
		$installment_plans   = Tables::name( 'installment_plans' );
		$installments        = Tables::name( 'installments' );
		$commerce_order_index = Tables::name( 'commerce_order_index' );
		$commerce_contact_rollups = Tables::name( 'commerce_contact_rollups' );
		$historical_resolution_batches = Tables::name( 'historical_resolution_batches' );
		$historical_resolution_items = Tables::name( 'historical_resolution_items' );
		$order_settlement_batches = Tables::name( 'order_settlement_batches' );
		$order_settlement_batch_items = Tables::name( 'order_settlement_batch_items' );
		$order_assumption_batches = Tables::name( 'order_assumption_batches' );
		$order_assumption_batch_items = Tables::name( 'order_assumption_batch_items' );
		$integrity_cases     = Tables::name( 'integrity_cases' );
		$rules               = Tables::name( 'rules' );
		$events              = Tables::name( 'events' );
		$mobile_sessions     = Tables::name( 'mobile_sessions' );
		$report_snapshots    = Tables::name( 'report_snapshots' );

		return array(
			"CREATE TABLE {$accounts} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				code varchar(100) DEFAULT '',
				name varchar(191) NOT NULL,
				account_type varchar(50) DEFAULT 'operating',
				currency varchar(10) DEFAULT '',
				status varchar(30) DEFAULT 'active',
				current_balance decimal(20,6) DEFAULT 0,
				year_total decimal(20,6) DEFAULT 0,
				lifetime_total decimal(20,6) DEFAULT 0,
				debt_total decimal(20,6) DEFAULT 0,
				consumption_total decimal(20,6) DEFAULT 0,
				notes longtext NULL,
				meta_json longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY code (code),
				KEY account_type (account_type),
				KEY status (status)
			) {$charset_collate};",
			"CREATE TABLE {$contacts} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				display_name varchar(191) NOT NULL,
				legal_name varchar(191) DEFAULT '',
				contact_type varchar(50) DEFAULT 'mixed',
				profile_origin varchar(30) DEFAULT 'external',
				wp_user_id bigint(20) unsigned DEFAULT NULL,
				is_customer tinyint(1) DEFAULT 0,
				is_employee tinyint(1) DEFAULT 0,
				is_supplier tinyint(1) DEFAULT 0,
				internal_use_profile tinyint(1) DEFAULT 0,
				supplier_kind varchar(30) DEFAULT '',
				email varchar(191) DEFAULT '',
				phone varchar(60) DEFAULT '',
				document_id varchar(60) DEFAULT '',
				payment_terms varchar(60) DEFAULT '',
				status varchar(30) DEFAULT 'active',
				search_index longtext NULL,
				notes longtext NULL,
				meta_json longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY contact_type (contact_type),
				KEY profile_origin (profile_origin),
				KEY wp_user_id (wp_user_id),
				KEY status (status)
			) {$charset_collate};",
			"CREATE TABLE {$documents} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				document_number varchar(100) DEFAULT '',
				document_type varchar(50) NOT NULL,
				source_type varchar(50) DEFAULT 'manual',
				account_id bigint(20) unsigned DEFAULT NULL,
				contact_id bigint(20) unsigned DEFAULT NULL,
				wp_user_id bigint(20) unsigned DEFAULT NULL,
				parent_document_id bigint(20) unsigned DEFAULT NULL,
				title varchar(191) NOT NULL,
				external_reference varchar(120) DEFAULT '',
				issue_date date DEFAULT NULL,
				due_date date DEFAULT NULL,
				currency varchar(10) DEFAULT '',
				total decimal(20,6) DEFAULT 0,
				paid_total decimal(20,6) DEFAULT 0,
				balance decimal(20,6) DEFAULT 0,
				operational_status varchar(50) DEFAULT '',
				financial_status varchar(50) DEFAULT 'draft',
				payment_status varchar(50) DEFAULT 'pending',
				financial_intent varchar(50) DEFAULT 'neutral',
				balance_nature varchar(50) DEFAULT 'neutral',
				category_key varchar(100) DEFAULT '',
				subcategory_key varchar(100) DEFAULT '',
				manual_override tinyint(1) DEFAULT 0,
				posted_at datetime DEFAULT NULL,
				search_index longtext NULL,
				notes longtext NULL,
				meta_json longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY document_type (document_type),
				KEY source_type (source_type),
				KEY account_id (account_id),
				KEY contact_id (contact_id),
				KEY financial_status (financial_status),
				KEY payment_status (payment_status),
				KEY financial_intent (financial_intent),
				KEY balance_nature (balance_nature),
				KEY issue_date (issue_date),
				KEY due_date (due_date)
			) {$charset_collate};",
			"CREATE TABLE {$document_files} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				document_id bigint(20) unsigned NOT NULL,
				attachment_id bigint(20) unsigned NOT NULL,
				file_kind varchar(50) DEFAULT 'supporting_document',
				title varchar(191) DEFAULT '',
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY document_id (document_id),
				KEY attachment_id (attachment_id),
				KEY file_kind (file_kind)
			) {$charset_collate};",
			"CREATE TABLE {$source_links} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				document_id bigint(20) unsigned NOT NULL,
				provider varchar(50) NOT NULL,
				object_type varchar(50) NOT NULL,
				external_id varchar(120) NOT NULL,
				external_ref varchar(191) DEFAULT '',
				sync_hash varchar(64) DEFAULT '',
				last_synced_at datetime DEFAULT NULL,
				last_seen_at datetime DEFAULT NULL,
				override_locked tinyint(1) DEFAULT 0,
				meta_json longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY provider_object_external (provider, object_type, external_id),
				KEY document_id (document_id),
				KEY last_synced_at (last_synced_at)
			) {$charset_collate};",
			"CREATE TABLE {$payments} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				payment_number varchar(100) DEFAULT '',
				payment_type varchar(50) DEFAULT 'collection',
				account_id bigint(20) unsigned DEFAULT NULL,
				contact_id bigint(20) unsigned DEFAULT NULL,
				status varchar(30) DEFAULT 'posted',
				payment_date date DEFAULT NULL,
				currency varchar(10) DEFAULT '',
				total decimal(20,6) DEFAULT 0,
				available_amount decimal(20,6) DEFAULT 0,
				method_key varchar(60) DEFAULT '',
				reference varchar(120) DEFAULT '',
				search_index longtext NULL,
				notes longtext NULL,
				meta_json longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY payment_type (payment_type),
				KEY account_id (account_id),
				KEY contact_id (contact_id),
				KEY status (status),
				KEY payment_date (payment_date)
			) {$charset_collate};",
			"CREATE TABLE {$payment_allocations} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				payment_id bigint(20) unsigned NOT NULL,
				document_id bigint(20) unsigned NOT NULL,
				currency varchar(10) DEFAULT '',
				amount decimal(20,6) DEFAULT 0,
				document_paid_before decimal(20,6) DEFAULT NULL,
				document_balance_before decimal(20,6) DEFAULT NULL,
				document_payment_status_before varchar(50) DEFAULT '',
				document_paid_after decimal(20,6) DEFAULT NULL,
				document_balance_after decimal(20,6) DEFAULT NULL,
				document_payment_status_after varchar(50) DEFAULT '',
				payment_available_before decimal(20,6) DEFAULT NULL,
				payment_available_after decimal(20,6) DEFAULT NULL,
				notes longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY payment_id (payment_id),
				KEY document_id (document_id)
			) {$charset_collate};",
			"CREATE TABLE {$employee_profiles} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				contact_id bigint(20) unsigned NOT NULL,
				wp_user_id bigint(20) unsigned DEFAULT NULL,
				employment_status varchar(30) DEFAULT 'active',
				salary_amount decimal(20,6) DEFAULT 0,
				salary_currency varchar(10) DEFAULT '',
				pay_frequency varchar(30) DEFAULT 'monthly',
				payday_mode varchar(30) DEFAULT 'monthday',
				payday_value int(11) DEFAULT 1,
				cycle_anchor_date date DEFAULT NULL,
				effective_from date DEFAULT NULL,
				next_payment_date date DEFAULT NULL,
				last_payment_date date DEFAULT NULL,
				default_account_id bigint(20) unsigned DEFAULT NULL,
				notes longtext NULL,
				meta_json longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY contact_id (contact_id),
				UNIQUE KEY wp_user_id (wp_user_id),
				KEY employment_status (employment_status),
				KEY pay_frequency (pay_frequency),
				KEY next_payment_date (next_payment_date),
				KEY default_account_id (default_account_id)
			) {$charset_collate};",
			"CREATE TABLE {$employee_advances} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				contact_id bigint(20) unsigned NOT NULL,
				wp_user_id bigint(20) unsigned DEFAULT NULL,
				employee_profile_id bigint(20) unsigned DEFAULT NULL,
				payment_id bigint(20) unsigned DEFAULT NULL,
				status varchar(30) DEFAULT 'active',
				total_amount decimal(20,6) DEFAULT 0,
				recovered_amount decimal(20,6) DEFAULT 0,
				balance decimal(20,6) DEFAULT 0,
				currency varchar(10) DEFAULT '',
				issued_at date DEFAULT NULL,
				expected_recovery_date date DEFAULT NULL,
				recovery_mode varchar(30) DEFAULT 'next_payroll',
				source_account_id bigint(20) unsigned DEFAULT NULL,
				reference varchar(120) DEFAULT '',
				notes longtext NULL,
				meta_json longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY contact_id (contact_id),
				KEY wp_user_id (wp_user_id),
				KEY employee_profile_id (employee_profile_id),
				KEY payment_id (payment_id),
				KEY status (status),
				KEY issued_at (issued_at),
				KEY expected_recovery_date (expected_recovery_date),
				KEY source_account_id (source_account_id)
			) {$charset_collate};",
			"CREATE TABLE {$payroll_periods} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				contact_id bigint(20) unsigned NOT NULL,
				wp_user_id bigint(20) unsigned DEFAULT NULL,
				employee_profile_id bigint(20) unsigned NOT NULL,
				title varchar(191) NOT NULL,
				frequency_key varchar(30) DEFAULT 'monthly',
				period_start date DEFAULT NULL,
				period_end date DEFAULT NULL,
				scheduled_payment_date date DEFAULT NULL,
				paid_at date DEFAULT NULL,
				payment_account_id bigint(20) unsigned DEFAULT NULL,
				payment_method_key varchar(60) DEFAULT 'payroll',
				gross_amount decimal(20,6) DEFAULT 0,
				advance_deduction_amount decimal(20,6) DEFAULT 0,
				other_deduction_amount decimal(20,6) DEFAULT 0,
				net_amount decimal(20,6) DEFAULT 0,
				currency varchar(10) DEFAULT '',
				status varchar(30) DEFAULT 'planned',
				document_id bigint(20) unsigned DEFAULT NULL,
				payment_id bigint(20) unsigned DEFAULT NULL,
				notes longtext NULL,
				meta_json longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY contact_id (contact_id),
				KEY wp_user_id (wp_user_id),
				KEY employee_profile_id (employee_profile_id),
				KEY frequency_key (frequency_key),
				KEY scheduled_payment_date (scheduled_payment_date),
				KEY status (status),
				KEY document_id (document_id),
				KEY payment_id (payment_id)
			) {$charset_collate};",
			"CREATE TABLE {$service_profiles} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				contact_id bigint(20) unsigned NOT NULL,
				account_id bigint(20) unsigned DEFAULT NULL,
				title varchar(191) NOT NULL,
				external_reference varchar(120) DEFAULT '',
				service_category varchar(60) DEFAULT 'general',
				amount decimal(20,6) DEFAULT 0,
				currency varchar(10) DEFAULT '',
				frequency_key varchar(30) DEFAULT 'monthly',
				start_date date DEFAULT NULL,
				next_issue_date date DEFAULT NULL,
				last_issued_date date DEFAULT NULL,
				default_due_days int(11) DEFAULT 0,
				status varchar(30) DEFAULT 'active',
				payment_terms varchar(60) DEFAULT '',
				notes longtext NULL,
				meta_json longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY contact_id (contact_id),
				KEY account_id (account_id),
				KEY frequency_key (frequency_key),
				KEY next_issue_date (next_issue_date),
				KEY status (status)
			) {$charset_collate};",
			"CREATE TABLE {$installment_plans} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				document_id bigint(20) unsigned DEFAULT NULL,
				contact_id bigint(20) unsigned DEFAULT NULL,
				plan_type varchar(50) DEFAULT 'loan',
				title varchar(191) NOT NULL,
				currency varchar(10) DEFAULT '',
				principal_amount decimal(20,6) DEFAULT 0,
				total_amount decimal(20,6) DEFAULT 0,
				balance decimal(20,6) DEFAULT 0,
				installment_count int(11) DEFAULT 0,
				frequency_key varchar(30) DEFAULT 'monthly',
				status varchar(30) DEFAULT 'active',
				start_date date DEFAULT NULL,
				end_date date DEFAULT NULL,
				notes longtext NULL,
				meta_json longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY document_id (document_id),
				KEY contact_id (contact_id),
				KEY plan_type (plan_type),
				KEY status (status)
			) {$charset_collate};",
			"CREATE TABLE {$installments} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				plan_id bigint(20) unsigned NOT NULL,
				sequence_no int(11) DEFAULT 0,
				title varchar(191) DEFAULT '',
				due_date date DEFAULT NULL,
				amount decimal(20,6) DEFAULT 0,
				paid_amount decimal(20,6) DEFAULT 0,
				balance decimal(20,6) DEFAULT 0,
				payment_status varchar(30) DEFAULT 'pending',
				paid_at datetime DEFAULT NULL,
				meta_json longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY plan_id (plan_id),
				KEY due_date (due_date),
				KEY payment_status (payment_status)
			) {$charset_collate};",
			"CREATE TABLE {$commerce_order_index} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				provider varchar(50) NOT NULL,
				external_order_id bigint(20) unsigned NOT NULL,
				order_number varchar(100) DEFAULT '',
				group_key varchar(191) NOT NULL,
				contact_id bigint(20) unsigned DEFAULT NULL,
				wp_user_id bigint(20) unsigned DEFAULT NULL,
				customer_email varchar(191) DEFAULT '',
				display_name varchar(191) DEFAULT '',
				issue_date date DEFAULT NULL,
				fiscal_year int(11) NOT NULL,
				status varchar(50) DEFAULT '',
				currency varchar(10) DEFAULT '',
				gross_total decimal(20,6) DEFAULT 0,
				paid_total decimal(20,6) DEFAULT 0,
				balance decimal(20,6) DEFAULT 0,
				item_count int(11) DEFAULT 0,
				is_open tinyint(1) DEFAULT 0,
				operationally_collectible tinyint(1) DEFAULT 0,
				is_historical_carryforward tinyint(1) DEFAULT 0,
				historical_resolution_status varchar(50) DEFAULT '',
				historical_resolution_note longtext NULL,
				historical_resolution_batch_id bigint(20) unsigned DEFAULT NULL,
				document_id bigint(20) unsigned DEFAULT NULL,
				source_link_id bigint(20) unsigned DEFAULT NULL,
				search_index longtext NULL,
				meta_json longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY provider_external_order (provider, external_order_id),
				KEY group_key (group_key),
				KEY fiscal_year (fiscal_year),
				KEY contact_id (contact_id),
				KEY wp_user_id (wp_user_id),
				KEY customer_email (customer_email),
				KEY issue_date (issue_date),
				KEY is_open (is_open),
				KEY operationally_collectible (operationally_collectible),
				KEY historical_resolution_status (historical_resolution_status),
				KEY document_id (document_id),
				KEY source_link_id (source_link_id)
			) {$charset_collate};",
			"CREATE TABLE {$commerce_contact_rollups} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				group_key varchar(191) NOT NULL,
				contact_id bigint(20) unsigned DEFAULT NULL,
				wp_user_id bigint(20) unsigned DEFAULT NULL,
				customer_email varchar(191) DEFAULT '',
				display_name varchar(191) DEFAULT '',
				fiscal_year int(11) NOT NULL,
				order_count int(11) DEFAULT 0,
				open_order_count int(11) DEFAULT 0,
				gross_total decimal(20,6) DEFAULT 0,
				paid_total decimal(20,6) DEFAULT 0,
				balance_total decimal(20,6) DEFAULT 0,
				collectible_balance_total decimal(20,6) DEFAULT 0,
				administratively_closed_balance decimal(20,6) DEFAULT 0,
				first_order_date date DEFAULT NULL,
				last_order_date date DEFAULT NULL,
				average_ticket decimal(20,6) DEFAULT 0,
				meta_json longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY group_fiscal_year (group_key, fiscal_year),
				KEY fiscal_year (fiscal_year),
				KEY contact_id (contact_id),
				KEY wp_user_id (wp_user_id),
				KEY customer_email (customer_email)
			) {$charset_collate};",
			"CREATE TABLE {$historical_resolution_batches} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				batch_key varchar(100) NOT NULL,
				fiscal_year_from int(11) DEFAULT 0,
				fiscal_year_to int(11) DEFAULT 0,
				status varchar(30) DEFAULT 'pending',
				reason_key varchar(60) DEFAULT '',
				note longtext NULL,
				item_count int(11) DEFAULT 0,
				balance_total decimal(20,6) DEFAULT 0,
				processed_count int(11) DEFAULT 0,
				processed_total decimal(20,6) DEFAULT 0,
				created_by bigint(20) unsigned DEFAULT NULL,
				meta_json longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY batch_key (batch_key),
				KEY fiscal_year_from (fiscal_year_from),
				KEY fiscal_year_to (fiscal_year_to),
				KEY status (status),
				KEY created_by (created_by)
			) {$charset_collate};",
			"CREATE TABLE {$historical_resolution_items} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				batch_id bigint(20) unsigned NOT NULL,
				order_index_id bigint(20) unsigned NOT NULL,
				provider varchar(50) DEFAULT '',
				external_order_id bigint(20) unsigned DEFAULT NULL,
				previous_status varchar(50) DEFAULT '',
				new_resolution_status varchar(50) DEFAULT '',
				balance_before decimal(20,6) DEFAULT 0,
				balance_after decimal(20,6) DEFAULT 0,
				note longtext NULL,
				meta_json longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY batch_id (batch_id),
				KEY order_index_id (order_index_id),
				KEY external_order_id (external_order_id)
			) {$charset_collate};",
			"CREATE TABLE {$order_settlement_batches} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				batch_key varchar(100) NOT NULL,
				contact_id bigint(20) unsigned NOT NULL,
				origin varchar(60) DEFAULT 'profile_settlement',
				mode varchar(30) DEFAULT 'standard',
				status varchar(30) DEFAULT 'pending',
				currency varchar(10) DEFAULT '',
				method_key varchar(60) DEFAULT '',
				preview_signature varchar(64) DEFAULT '',
				total_received decimal(20,6) DEFAULT 0,
				total_covered decimal(20,6) DEFAULT 0,
				discount_total decimal(20,6) DEFAULT 0,
				item_count int(11) DEFAULT 0,
				processed_count int(11) DEFAULT 0,
				processed_total decimal(20,6) DEFAULT 0,
				created_by bigint(20) unsigned DEFAULT NULL,
				meta_json longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY batch_key (batch_key),
				KEY contact_id (contact_id),
				KEY origin (origin),
				KEY status (status),
				KEY preview_signature (preview_signature),
				KEY created_by (created_by)
			) {$charset_collate};",
			"CREATE TABLE {$order_settlement_batch_items} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				batch_id bigint(20) unsigned NOT NULL,
				sort_index int(11) DEFAULT 0,
				source_kind varchar(30) DEFAULT 'current_live',
				provider varchar(50) DEFAULT '',
				external_order_id bigint(20) unsigned DEFAULT NULL,
				document_id bigint(20) unsigned DEFAULT NULL,
				order_number varchar(100) DEFAULT '',
				issue_date date DEFAULT NULL,
				balance_before decimal(20,6) DEFAULT 0,
				cover_amount decimal(20,6) DEFAULT 0,
				customer_paid_amount decimal(20,6) DEFAULT 0,
				discount_amount decimal(20,6) DEFAULT 0,
				expected_balance_after decimal(20,6) DEFAULT 0,
				status varchar(30) DEFAULT 'pending',
				error_message longtext NULL,
				meta_json longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY batch_id (batch_id),
				KEY sort_index (sort_index),
				KEY source_kind (source_kind),
				KEY provider (provider),
				KEY external_order_id (external_order_id),
				KEY document_id (document_id),
				KEY issue_date (issue_date),
				KEY status (status)
			) {$charset_collate};",
			"CREATE TABLE {$order_assumption_batches} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				batch_key varchar(100) NOT NULL,
				contact_id bigint(20) unsigned NOT NULL,
				origin varchar(60) DEFAULT 'profile_order_assumption',
				mode varchar(30) DEFAULT 'expense',
				status varchar(30) DEFAULT 'pending',
				preview_signature varchar(64) DEFAULT '',
				assumed_total decimal(20,6) DEFAULT 0,
				current_total decimal(20,6) DEFAULT 0,
				historical_total decimal(20,6) DEFAULT 0,
				item_count int(11) DEFAULT 0,
				blocked_count int(11) DEFAULT 0,
				processed_count int(11) DEFAULT 0,
				created_by bigint(20) unsigned DEFAULT NULL,
				meta_json longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY batch_key (batch_key),
				KEY contact_id (contact_id),
				KEY origin (origin),
				KEY mode (mode),
				KEY status (status),
				KEY preview_signature (preview_signature),
				KEY created_by (created_by)
			) {$charset_collate};",
			"CREATE TABLE {$order_assumption_batch_items} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				batch_id bigint(20) unsigned NOT NULL,
				sort_index int(11) DEFAULT 0,
				source_kind varchar(30) DEFAULT 'current_live',
				provider varchar(50) DEFAULT '',
				external_order_id bigint(20) unsigned DEFAULT NULL,
				document_id bigint(20) unsigned DEFAULT NULL,
				order_number varchar(100) DEFAULT '',
				issue_date date DEFAULT NULL,
				balance_before decimal(20,6) DEFAULT 0,
				status varchar(30) DEFAULT 'pending',
				error_message longtext NULL,
				meta_json longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY batch_id (batch_id),
				KEY sort_index (sort_index),
				KEY source_kind (source_kind),
				KEY provider (provider),
				KEY external_order_id (external_order_id),
				KEY document_id (document_id),
				KEY issue_date (issue_date),
				KEY status (status)
			) {$charset_collate};",
			"CREATE TABLE {$integrity_cases} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				case_key varchar(191) NOT NULL,
				case_type varchar(80) NOT NULL,
				severity varchar(20) NOT NULL DEFAULT 'medium',
				status varchar(20) NOT NULL DEFAULT 'open',
				contact_id bigint(20) unsigned DEFAULT NULL,
				contact_label varchar(191) DEFAULT '',
				external_order_id bigint(20) unsigned DEFAULT NULL,
				order_number varchar(100) DEFAULT '',
				document_id bigint(20) unsigned DEFAULT NULL,
				payment_id bigint(20) unsigned DEFAULT NULL,
				batch_id bigint(20) unsigned DEFAULT NULL,
				amount decimal(20,6) DEFAULT 0,
				currency varchar(10) DEFAULT '',
				summary varchar(255) DEFAULT '',
				search_index longtext NULL,
				payload_json longtext NULL,
				first_detected_at datetime NOT NULL,
				last_detected_at datetime NOT NULL,
				last_scanned_at datetime NOT NULL,
				status_changed_at datetime DEFAULT NULL,
				status_changed_by bigint(20) unsigned DEFAULT NULL,
				status_note longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY case_key (case_key),
				KEY case_type (case_type),
				KEY severity (severity),
				KEY status (status),
				KEY contact_id (contact_id),
				KEY external_order_id (external_order_id),
				KEY document_id (document_id),
				KEY payment_id (payment_id),
				KEY batch_id (batch_id),
				KEY last_detected_at (last_detected_at)
			) {$charset_collate};",
			"CREATE TABLE {$rules} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				rule_name varchar(191) NOT NULL,
				priority int(11) DEFAULT 100,
				scope_type varchar(50) DEFAULT 'document',
				source_type varchar(50) DEFAULT '',
				is_active tinyint(1) DEFAULT 1,
				conditions_json longtext NULL,
				actions_json longtext NULL,
				notes longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY priority (priority),
				KEY scope_type (scope_type),
				KEY source_type (source_type),
				KEY is_active (is_active)
			) {$charset_collate};",
			"CREATE TABLE {$events} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				entity_type varchar(50) NOT NULL,
				entity_id bigint(20) unsigned DEFAULT NULL,
				event_type varchar(80) NOT NULL,
				actor_user_id bigint(20) unsigned DEFAULT NULL,
				message varchar(255) DEFAULT '',
				search_index longtext NULL,
				payload_json longtext NULL,
				created_at datetime NOT NULL,
				PRIMARY KEY  (id),
				KEY entity_type (entity_type),
				KEY entity_id (entity_id),
				KEY event_type (event_type),
				KEY created_at (created_at)
			) {$charset_collate};",
			"CREATE TABLE {$mobile_sessions} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				user_id bigint(20) unsigned NOT NULL,
				device_name varchar(191) DEFAULT '',
				platform varchar(30) DEFAULT 'ios',
				app_version varchar(50) DEFAULT '',
				access_token_hash char(64) NOT NULL,
				refresh_token_hash char(64) NOT NULL,
				auth_state_hash char(64) DEFAULT '',
				access_expires_at datetime NOT NULL,
				refresh_expires_at datetime NOT NULL,
				last_used_at datetime DEFAULT NULL,
				last_ip varchar(100) DEFAULT '',
				user_agent varchar(255) DEFAULT '',
				revoked_at datetime DEFAULT NULL,
				meta_json longtext NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY access_token_hash (access_token_hash),
				UNIQUE KEY refresh_token_hash (refresh_token_hash),
				KEY user_id (user_id),
				KEY access_expires_at (access_expires_at),
				KEY refresh_expires_at (refresh_expires_at),
				KEY revoked_at (revoked_at)
			) {$charset_collate};",
			"CREATE TABLE {$report_snapshots} (
				id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
				report_key varchar(60) NOT NULL DEFAULT 'financial_master_monthly',
				month_key varchar(7) NOT NULL,
				range_from date NOT NULL,
				range_to date NOT NULL,
				fiscal_context_json longtext NULL,
				version_no int(11) NOT NULL DEFAULT 1,
				is_official tinyint(1) NOT NULL DEFAULT 0,
				status varchar(30) NOT NULL DEFAULT 'generated',
				filters_json longtext NULL,
				payload_json longtext NULL,
				created_by bigint(20) unsigned DEFAULT NULL,
				created_at datetime NOT NULL,
				updated_at datetime NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY report_month_version (report_key, month_key, version_no),
				KEY report_month (report_key, month_key),
				KEY month_key (month_key),
				KEY is_official (is_official),
				KEY status (status),
				KEY created_by (created_by)
			) {$charset_collate};",
		);
	}
}
